### PR TITLE
Spark Name: Changed getsparknames for working with disablewallet=1

### LINKED ISSUE #1625: Spark Name: getsparknames does not work when disablewallet=1

### PR DESCRIPTION
**Pull request by levoncrypto**
Fixes #1625

### CODE REVIEW

**Comment by justanwar** [comment]
Tested, `getsparknames` RPC works as expected with `disablewallet=1`

**Review by levonpetrosyan93 — APPROVED** [review]

File: src/rpc/blockchain.cpp [hunk 1]
```diff
@@ -224,6 +224,71 @@ UniValue getsparknamedata(const JSONRPCRequest& request)
...
+{
+    if (request.fHelp || request.params.size() > 1) {
+        throw std::runtime_error(
+            "getsparknames [fOnlyOwn] \n"
+            "\nReturns a list of all Spark names and additional info.\n"
+            "\nArguments:\n"
+            "1. onlyown       (boolean, optional, default=false) Display only the spark names that belong to this wallet\n"
+            "\nResult:\n"
+            "[\n"
+            "  \"Name (string)\n"
```
Comment (aleflm) [inline src/rpc/blockchain.cpp:237]: Shouldn't we have a " here?

**Review by aleflm — APPROVED** [review]
LGTM.
